// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjbifhpjzzjrdxenzvfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqYmlmaHBqenpqcmR4ZW56dmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTk2MTYsImV4cCI6MjA2MTEzNTYxNn0.2gX9GrgEHXJtgYRyscCoWZbro88ISe8faTYBjDpbwek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);